---
name: Check python-basics course notebooks will run.

on:
  pull_request:
    paths: python-intro/**
  push:
    branches:
      - "main"
    tags:
      - "isc*"

jobs:
  run-notebooks:
    name: run-notebooks-${{ matrix.py }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: true
      matrix:
        os:
          - Ubuntu
        py:
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
      - name: Install notebook processor.
        run: python -m pip install .scripts/notebook-processor[kernel]
      - name: Install course dependencies
        run: python -m pip install -r .scripts/requirements/python-basics-requirements.txt
      - name: Run the processor.
        run: python -m notebook_processor python-intro --kernel-name=python3
